name: Docker Build and Compose

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t streamlite .

      - name: Run Docker Compose
        run: docker-compose up -d

      - name: Check containers
        run: docker ps
